---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_OIDC_HMAC_SECRET: "{{ .AUTHELIA_OIDC_HMAC_SECRET }}"
        AUTHELIA_OIDC_JWKS_KEY: "{{ .AUTHELIA_OIDC_JWKS_KEY }}"
        AUTHELIA_OIDC_CLOUDFLARE_CLIENT_ID: "{{ .AUTHELIA_OIDC_CLOUDFLARE_CLIENT_ID }}"
        AUTHELIA_OIDC_CLOUDFLARE_CLIENT_SECRET_DIGEST: "{{ .AUTHELIA_OIDC_CLOUDFLARE_CLIENT_SECRET_DIGEST }}"
        AUTHELIA_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_RESET_PASSWORD_JWT_SECRET }}"
        MAILGUN_SMTP_USERNAME: "{{ .MAILGUN_SMTP_USERNAME }}"
        MAILGUN_SMTP_PASSWORD: "{{ .MAILGUN_SMTP_PASSWORD }}"
        CLOUDFLARE_TEAM: "{{ .CLOUDFLARE_TEAM }}"
        LLDAP_ADMIN_PASSWORD: "{{ .LLDAP_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: mailgun
    - extract:
        key: cloudflare
    - extract:
        key: lldap
