---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rabbitmq-secret
    template:
      engineVersion: v2
      data:
        RABBITMQ_USERNAME: "{{ .RABBITMQ_USERNAME }}"
        RABBITMQ_PASSWORD: "{{ .RABBITMQ_PASSWORD }}"
  dataFrom:
    - extract:
        key: rabbitmq
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-load-definition
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rabbitmq-load-definition-secret
    template:
      engineVersion: v2
      data:
        load_definition.json: |
          {
            "users": [
              {
                "name": "{{ .GRAFANA_ONCALL_RABBITMQ_USERNAME }}",
                "password": "{{ .GRAFANA_ONCALL_RABBITMQ_PASSWORD }}"
              }
            ]
          }
  dataFrom:
    - extract:
        key: grafana-oncall
