---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rabbitmq-secret
    template:
      engineVersion: v2
      data:
        RABBITMQ_USERNAME: "{{ .RABBITMQ_USERNAME }}"
        RABBITMQ_PASSWORD: "{{ .RABBITMQ_PASSWORD }}"
  dataFrom:
    - extract:
        key: rabbitmq
