---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: rabbitmq-dashboard
        group: external
        url: "https://${CLOUDFLARE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
        headers:
          "CF-Access-Client-Id": "$${cloudflareClientId}"
          "CF-Access-Client-Secret": "$${cloudflareSecretKey}"
        interval: 15s
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
      - name: rabbitmq
        group: infrastructure
        url: tcp://rabbitmq.rabbitmq.svc.cluster.local:5672
        interval: 15s
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
