---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: rabbitmq
        group: infrastructure
        url: tcp://rabbitmq.rabbitmq.svc.cluster.local:5672
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
