---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq
      version: 15.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    auth:
      username: admin
      existingPasswordSecret: rabbitmq-secret
      existingSecretPasswordKey: RABBITMQ_PASSWORD
    clustering:
      enabled: false
    extraEnvVars:
      - name: RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS
        value: "true"
    persistence:
      enabled: true
      existingClaim: rabbitmq-data
    resources:
      requests:
        cpu: 10m
        memory: 204Mi
      limits:
        memory: 512Mi
