---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-dashboard
spec:
  ingressClassName: internal
  rules:
    - host: "${CLOUDFLARE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emqx
                port:
                  number: 18083
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-websocket
spec:
  ingressClassName: internal
  rules:
    - host: "${CLOUDFLARE_MQTT_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
      http:
        paths:
          - path: /mqtt
            pathType: Prefix
            backend:
              service:
                name: emqx
                port:
                  number: 8083
