[makejinja]
exclude_patterns = []
import_paths = ["./.taskfiles/scripts"]
loaders = ["plugin:Plugin"]
jinja_suffix = ".j2"
force = true
undefined = "chainable"

[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "#|"
comment_end = "#|"
variable_start = "#{"
variable_end = "}#"
