---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        EMQX_MQTT_GATUS_USERNAME: "{{ .EMQX_MQTT_GATUS_USERNAME }}"
        EMQX_MQTT_GATUS_PASSWORD: "{{ .EMQX_MQTT_GATUS_PASSWORD }}"
  dataFrom:
    - extract:
        key: gatus
    - extract:
        key: emqx
    - extract:
        key: pushover
