---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oncall
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-oncall-secret
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .GRAFANA_ONCALL_SECRET_KEY }}"
        MIRAGE_SECRET_KEY: "{{ .GRAFANA_ONCALL_MIRAGE_SECRET_KEY }}"
        MIRAGE_CIPHER_IV: "{{ .GRAFANA_ONCALL_MIRAGE_CIPHER_IV }}"
        REDIS_USERNAME: "{{ .GRAFANA_ONCALL_REDIS_USERNAME }}"
        REDIS_PASSWORD: "{{ .GRAFANA_ONCALL_REDIS_PASSWORD }}"
        GRAFANA_CLOUD_ONCALL_TOKEN: "{{ .GRAFANA_ONCALL_CLOUD_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana-oncall
