---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-oncall-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: grafana-oncall
        group: infrastructure
        url: tcp://grafana-oncall.observability.svc.cluster.local:8080
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
