---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redis
  namespace: flux-system
spec:
  targetNamespace: redis
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/staging/main/service/apps/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
