---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
    - name: external-secrets-stores
    - name: lldap
    - name: cloudflare-access-config
  path: ./kubernetes/staging/main/service/core/authentication/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_SUBDOMAIN: &subdomain auth
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: authelia
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_DECISION: non_identity
      GATUS_SUBDOMAIN: *subdomain
