---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy:
      - alertname
      - job
    groupInterval: 10m
    groupWait: 1m
    receiver: pushover
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: "="
      - receiver: heartbeat
        groupInterval: 5m
        groupWait: 0s
        repeatInterval: 5m
        matchers:
          - name: alertname
            value: Watchdog
            matchType: "="
      - receiver: pushover-gatus
        matchers:
          - name: source
            value: gatus
            matchType: "="
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: "="
      targetMatch:
        - name: severity
          value: warning
          matchType: "="
  receivers:
    - name: "null"
    - name: heartbeat
      webhookConfigs:
        - urlSecret:
            name: &secret alertmanager-secret
            key: ALERTMANAGER_HEARTBEAT_URL
    - name: pushover
      pushoverConfigs:
        - html: true
          message: &message |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if gt (len .Labels.SortedPairs) 0 }}
                <small>
                  {{- range .Labels.SortedPairs }}
                    <b>{{ .Name }}:</b> {{ .Value }}
                  {{- end }}
                </small>
              {{- end }}
              {{- if ne .Annotations.gatus_url "" }}
                <a href="{{ .Annotations.gatus_url }}">View in Gatus</a>
              {{- end }}
              {{- if ne .Annotations.grafana_url "" }}
                <a href="{{ .Annotations.grafana_url }}">View in Grafana</a>
              {{- end }}
              {{- if ne .Annotations.prometheus_url "" }}
                <a href="{{ .Annotations.prometheus_url }}">View in Prometheus</a>
              {{- end }}
            {{- end }}
          priority: &priority |-
            {{ if eq .Status "firing" }}{{ if .CommonLabels.severity }}{{ if eq .CommonLabels.severity "critical" }}2{{ else }}1{{ end }}{{ else }}1{{ end }}{{ else }}0{{ end }}
          sendResolved: true
          sound: gamelan
          title: &title >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          ttl: 3600s
          token:
            name: *secret
            key: ALERTMANAGER_PUSHOVER_TOKEN
          userKey:
            name: *secret
            key: PUSHOVER_USER_KEY
          urlTitle: View in Alertmanager
    - name: pushover-gatus
      pushoverConfigs:
        - html: true
          message: *message
          priority: *priority
          sendResolved: true
          sound: gamelan
          title: *title
          ttl: 3600s
          token:
            name: *secret
            key: GATUS_PUSHOVER_TOKEN
          userKey:
            name: *secret
            key: PUSHOVER_USER_KEY
          urlTitle: View in Alertmanager
