---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name alertmanager-data
  labels:
    app.kubernetes.io/name: *name
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name prometheus-data
  labels:
    app.kubernetes.io/name: *name
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
