---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: external
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${CLOUDFLARE_DOMAIN}${GATUS_PATH:-/}"
        headers:
          "CF-Access-Client-Id": "$${cloudflareClientId}"
          "CF-Access-Client-Secret": "$${cloudflareSecretKey}"
        interval: 15s
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
