---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-oncall-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
