---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-secret
    template:
      engineVersion: v2
      data:
        redis-password: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: redis
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-acl
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-acl-secret
    template:
      engineVersion: v2
      data:
        users.acl: |
          user oncall on #{{ .GRAFANA_ONCALL_REDIS_HASHED_PASSWORD }} +@all -@admin
  dataFrom:
    - extract:
        key: grafana-oncall
