---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 20.6.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    architecture: standalone
    auth:
      enabled: true
      sentinel: false
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
      usePasswordFiles: false
    master:
      persistence:
        enabled: true
        existingClaim: redis-data
    resources:
      requests:
        cpu: 10m
        memory: 204Mi
      limits:
        memory: 512Mi
