---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-oncall-config
data:
  BASE_URL: "http://${CLOUDFLARE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
  DJANGO_SETTINGS_MODULE: settings.helm
  AMIXR_DJANGO_ADMIN_PATH: admin
  OSS: "True"
  DETACHED_INTEGRATIONS_SERVER: "False"
  BROKER_TYPE: rabbitmq
  GRAFANA_API_URL: "https://monitoring.${CLOUDFLARE_DOMAIN}"
  UWSGI_LISTEN: "1024"
  FEATURE_SLACK_INTEGRATION_ENABLED: "False"
  FEATURE_TELEGRAM_INTEGRATION_ENABLED: "False"
  CELERY_WORKER_QUEUE: "default,critical,long,webhook,retry,celery,grafana"
  CELERY_WORKER_CONCURRENCY: "1"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  DATABASE_TYPE: sqlite3
  DATABASE_NAME: /data/oncall.db
  RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: oncall
  RABBITMQ_PROTOCOLL: amqp
  FEATURE_EMAIL_INTEGRATION_ENABLED: "False"
  FEATURE_PROMETHEUS_EXPORTER_ENABLED: "False"
