---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-zero-trust-operator
  namespace: flux-system
spec:
  interval: 2h
  url: https://github.com/bojanzelic/cloudflare-zero-trust-operator
  ref:
    commit: ec6362605b75cd91b7f83f54ab6bf9d9230caa37
