---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
    - name: external-secrets-stores
    - name: kube-prometheus-stack-prometheus-access
    - name: kube-prometheus-stack-alertmanager-access
  path: ./kubernetes/staging/main/service/core/observability/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      CLOUDFLARE_PROMETHEUS_SUBDOMAIN: prometheus
      CLOUDFLARE_ALERTMANAGER_SUBDOMAIN: alertmanager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack-prometheus-access
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudflare-access-config
  path: ./kubernetes/staging/main/service/core/observability/kube-prometheus-stack/access
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: &subdomain prometheus
      CLOUDFLARE_SUBDOMAIN: *subdomain
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
      GATUS_SUBDOMAIN: *subdomain
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack-alertmanager-access
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudflare-access-config
  path: ./kubernetes/staging/main/service/core/observability/kube-prometheus-stack/access
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: &subdomain alertmanager
      CLOUDFLARE_SUBDOMAIN: *subdomain
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
      GATUS_SUBDOMAIN: *subdomain
