---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx
  namespace: flux-system
spec:
  targetNamespace: emqx
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
  path: ./kubernetes/staging/main/service/apps/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx-cluster
  namespace: flux-system
spec:
  targetNamespace: emqx
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: emqx
    - name: external-secrets-stores
    - name: cloudflare-access-groups
  path: ./kubernetes/staging/main/service/apps/emqx/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: &subdomain emqx
      CLOUDFLARE_SUBDOMAIN: *subdomain
      CLOUDFLARE_MQTT_SUBDOMAIN: mqtt
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
