---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  url: "https://github.com/kadaan/homelab"
  secretRef:
    name: github-deploy-key
  ref:
    branch: "main"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes/staging/main
    !/kubernetes/staging/shared
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-shared
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/staging/shared
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/staging/main/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
