---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-oncall
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      engine:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: &image
              repository: grafana/oncall
              tag: v1.13.11@sha256:159b6b836fed0c9b61ff4014ad65c05b56500f31283c42de97dbe58679d33391
            envFrom: &envFrom
              - configMapRef:
                  name: grafana-oncall-config
              - secretRef:
                  name: grafana-oncall-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 60
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ready/
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources: &resources
              requests:
                cpu: 25m
              limits:
                memory: 256M
      celery:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: *image
            envFrom: *envFrom
            command: ["./celery_with_exporter.sh"]
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [
                      "bash",
                      "-c",
                      "celery -A engine inspect ping -d celery@$HOSTNAME"
                    ]
                  initialDelaySeconds: 30
                  periodSeconds: 300
                  timeoutSeconds: 10
                  failureThreshold: 3
            securityContext: *securityContext
            resources: *resources
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: engine
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${CLOUDFLARE_DOMAIN}"
        hosts:
          - host: "${CLOUDFLARE_SUBDOMAIN:-${APP}}.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      database:
        existingClaim: grafana-oncall-data
        globalMounts:
          - path: /data
      engine-tmpfs:
        type: emptyDir
        advancedMounts:
          engine:
            app:
              - path: /tmp
      celery-tmpfs:
        type: emptyDir
        advancedMounts:
          celery:
            app:
              - path: /tmp
