---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rabbitmq
  namespace: flux-system
spec:
  targetNamespace: rabbitmq
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/staging/main/service/apps/rabbitmq/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: rabbitmq
      CLOUDFLARE_SUBDOMAIN: queue
      CLOUDFLARE_ZEROTRUST_ACCESS_GROUP_NAME: oidc-admin
