# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: "v1.9.0"
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: "v1.32.0"

clusterName: "staging"
endpoint: https://192.168.2.80:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - "192.168.2.80"
  - "127.0.0.1"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "192.168.2.100"
    installDisk: "/dev/sda"
    talosImageURL: "factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba"
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:1c:42:07:d3:ef"
        dhcp: true
        mtu: 1500
        vip:
          ip: "192.168.2.80"

# Global patches
patches:
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/dns.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/ntp.yaml"
  - "@./patches/global/openebs-local.yaml"
  - "@./patches/global/sysctl.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/etcd.yaml"
