---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress.yaml
  - ./networkpolicy.yaml
  - ../../../../../../shared/templates/cloudflare/zero-trust
  - ../../../../../../shared/templates/gatus/external
