---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "e2e"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  # archlinux:
  #   name: workstation (archlinux)
  #   runs-on: ubuntu-latest
  #   container:
  #     image: greyltc/archlinux-aur:yay
  #     options: --user root
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Test Arch dependencies
  #       shell: bash
  #       run: >-
  #         sudo -E -u ab -D~ bash -c '
  #         cd $GITHUB_WORKSPACE;
  #         yay -Syu --needed --noconfirm --noprogressbar go-task;
  #         go-task workstation:arch
  #         '

  # generic-linux:
  #   name: workstation (generic-linux)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Homebrew
  #       id: setup-homebrew
  #       uses: Homebrew/actions/setup-homebrew@master

  #     - name: Setup Workflow Tools
  #       shell: bash
  #       run: brew install go-task

  #     - name: Run Workstation Generic linux tasks
  #       shell: bash
  #       run: task workstation:generic-linux

  configure:
    name: configure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config-files:
          - talos
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'

      - name: Run configure task
        run: devbox run -- task configure --yes

      - name: Run clean
        shell: bash
        run: task bootstrap:clean
