---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Kubeconform"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'

      - name: Run kubeconform
        run: ./scripts/kubernetes/kubeconform.sh ${{ env.KUBERNETES_DIR }}
